branches:
  # This is where pull requests from "bors r+" are built.
  - staging
  # This is where pull requests from "bors try" are built.
  - trying

sudo: required
dist: trusty

language: node_js

node_js:
  - "6"

addons:
  chrome: stable

env:
    - EMBER_VERSION=default
    - EMBER_VERSION=release
matrix:
  fast_finish: true

before_install:
    # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - "npm config set spin false"
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:7357 &
      

install:
    - cd $(./.ci_helper.sh name)
    - npm install

script:
    - ember test
